// A simple data API that will be used to get the data for our
// components. On a real website, a more robust data fetching
// solution would be more appropriate.
const Response = {
    players: [
      { id: 1, name: "Ben Blocker", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum." },
      { id: 2, name: "Dave Defender", description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)." },
      { id: 3, name: "Sam Sweeper", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce diam nisi, tempor ut massa sed, laoreet ultrices neque. Quisque id volutpat odio. Cras sed lorem fringilla, mattis orci nec, rutrum lorem. Donec eu iaculis nisi, et euismod nibh. Phasellus placerat vel ligula eget malesuada. Phasellus congue sem metus, a imperdiet augue imperdiet quis. Donec mattis scelerisque nisi nec commodo. Sed pellentesque lacinia neque ut pellentesque. Sed ut massa varius orci iaculis interdum. Quisque in viverra purus. In hac habitasse platea dictumst. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus." },
      { id: 4, name: "Matt Midfielder", description: "Suspendisse vulputate euismod nisi sed eleifend. Donec in dignissim turpis, vitae posuere tellus. Sed bibendum erat vel lectus vehicula, nec ultrices nunc semper. Donec tempor, risus a aliquet euismod, metus ex congue sapien, in volutpat metus augue vel quam. Curabitur ut pretium massa. Donec et orci ac nisi fringilla ullamcorper eget sit amet ipsum. Donec scelerisque bibendum urna, id sodales tellus. Maecenas aliquet mauris in lacus pulvinar, id lobortis arcu mattis. In eu dapibus tortor." },
      { id: 5, name: "William Winger", description: "Ut molestie dolor eget felis dignissim, eget venenatis felis ultrices. Integer aliquet rutrum massa, sed accumsan mauris aliquet non. Sed ac sapien posuere, porttitor mi ac, laoreet dolor. Mauris placerat lacus augue, et maximus lectus aliquam vel. Fusce maximus est non diam molestie, nec bibendum turpis accumsan. Nullam condimentum diam nec risus ultrices, nec posuere nunc consequat. Ut nec lacinia enim. Duis sed urna mauris. Curabitur eleifend nulla et arcu mollis aliquam. Nunc iaculis felis velit, eu vehicula lacus suscipit eget." },
      { id: 6, name: "Fillipe Forward", description: "Etiam sodales enim ac convallis posuere. Maecenas nec tempus leo, vel dignissim est. Proin arcu leo, placerat lacinia lorem at, dictum tincidunt dolor. Suspendisse nec dui quis risus dapibus sodales. Praesent tincidunt, sem et efficitur faucibus, lorem libero lacinia nisl, vitae mattis lectus erat et diam. Nullam faucibus risus odio, vitae rhoncus ex volutpat id. Vestibulum imperdiet velit orci, a consequat ante mollis non. Etiam sagittis sapien felis, non molestie sem luctus ac." }
    ],
    all: function() { return this.players}
  }
  
export default Response
  